# Generated by Django 4.0 on 2021-12-13 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NoteShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.user'),
        ),
    ]
