# Generated by Django 4.0 on 2021-12-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NoteShare', '0004_alter_note_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
